/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ApiTransactionsSellPostRequest
 */
export interface ApiTransactionsSellPostRequest {
  /**
   * 要卖出的资产ID
   * @type {number}
   * @memberof ApiTransactionsSellPostRequest
   */
  asset_id: number
  /**
   * 卖出数量
   * @type {number}
   * @memberof ApiTransactionsSellPostRequest
   */
  quantity: number
  /**
   * 卖出日期（YYYY-MM-DD格式）
   * @type {string}
   * @memberof ApiTransactionsSellPostRequest
   */
  date: string
  /**
   * 交易描述（可选）
   * @type {string}
   * @memberof ApiTransactionsSellPostRequest
   */
  description?: string
}
