/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ApiAnalysisDailyCashBalanceGet200ResponseDataAnalysisPeriod } from './api-analysis-daily-cash-balance-get200-response-data-analysis-period'
// May contain unused imports in some cases
// @ts-ignore
import type { ApiAnalysisDailyCashBalanceGet200ResponseDataAssetInfo } from './api-analysis-daily-cash-balance-get200-response-data-asset-info'
// May contain unused imports in some cases
// @ts-ignore
import type { ApiAnalysisDailyCashBalanceGet200ResponseDataDailyBalancesInner } from './api-analysis-daily-cash-balance-get200-response-data-daily-balances-inner'
// May contain unused imports in some cases
// @ts-ignore
import type { ApiAnalysisDailyCashBalanceGet200ResponseDataSummary } from './api-analysis-daily-cash-balance-get200-response-data-summary'

/**
 *
 * @export
 * @interface ApiAnalysisDailyCashBalanceGet200ResponseData
 */
export interface ApiAnalysisDailyCashBalanceGet200ResponseData {
  /**
   *
   * @type {ApiAnalysisDailyCashBalanceGet200ResponseDataAssetInfo}
   * @memberof ApiAnalysisDailyCashBalanceGet200ResponseData
   */
  asset_info?: ApiAnalysisDailyCashBalanceGet200ResponseDataAssetInfo
  /**
   *
   * @type {ApiAnalysisDailyCashBalanceGet200ResponseDataAnalysisPeriod}
   * @memberof ApiAnalysisDailyCashBalanceGet200ResponseData
   */
  analysis_period?: ApiAnalysisDailyCashBalanceGet200ResponseDataAnalysisPeriod
  /**
   *
   * @type {string}
   * @memberof ApiAnalysisDailyCashBalanceGet200ResponseData
   */
  initial_holding?: string
  /**
   *
   * @type {string}
   * @memberof ApiAnalysisDailyCashBalanceGet200ResponseData
   */
  final_holding?: string
  /**
   *
   * @type {string}
   * @memberof ApiAnalysisDailyCashBalanceGet200ResponseData
   */
  total_change?: string
  /**
   *
   * @type {Array<ApiAnalysisDailyCashBalanceGet200ResponseDataDailyBalancesInner>}
   * @memberof ApiAnalysisDailyCashBalanceGet200ResponseData
   */
  daily_balances?: Array<ApiAnalysisDailyCashBalanceGet200ResponseDataDailyBalancesInner>
  /**
   *
   * @type {ApiAnalysisDailyCashBalanceGet200ResponseDataSummary}
   * @memberof ApiAnalysisDailyCashBalanceGet200ResponseData
   */
  summary?: ApiAnalysisDailyCashBalanceGet200ResponseDataSummary
}
