/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiAssetTypesPostRequest
 */
export interface ApiAssetTypesPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiAssetTypesPostRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ApiAssetTypesPostRequest
     */
    'unit': string;
    /**
     * 
     * @type {string}
     * @memberof ApiAssetTypesPostRequest
     */
    'description'?: string;
}

