/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ApiAnalysisDailyCashBalanceGet200ResponseDataSummary
 */
export interface ApiAnalysisDailyCashBalanceGet200ResponseDataSummary {
  /**
   *
   * @type {string}
   * @memberof ApiAnalysisDailyCashBalanceGet200ResponseDataSummary
   */
  total_in_amount?: string
  /**
   *
   * @type {string}
   * @memberof ApiAnalysisDailyCashBalanceGet200ResponseDataSummary
   */
  total_out_amount?: string
  /**
   *
   * @type {number}
   * @memberof ApiAnalysisDailyCashBalanceGet200ResponseDataSummary
   */
  total_transactions?: number
  /**
   *
   * @type {number}
   * @memberof ApiAnalysisDailyCashBalanceGet200ResponseDataSummary
   */
  days_with_activity?: number
}
