/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ApiAnalysisAssetHoldingGet200ResponseDataHoldingAnalysis
 */
export interface ApiAnalysisAssetHoldingGet200ResponseDataHoldingAnalysis {
  /**
   *
   * @type {string}
   * @memberof ApiAnalysisAssetHoldingGet200ResponseDataHoldingAnalysis
   */
  initial_holding?: string
  /**
   *
   * @type {string}
   * @memberof ApiAnalysisAssetHoldingGet200ResponseDataHoldingAnalysis
   */
  final_holding?: string
  /**
   *
   * @type {string}
   * @memberof ApiAnalysisAssetHoldingGet200ResponseDataHoldingAnalysis
   */
  total_change?: string
  /**
   *
   * @type {Array<object>}
   * @memberof ApiAnalysisAssetHoldingGet200ResponseDataHoldingAnalysis
   */
  daily_analysis?: Array<object>
  /**
   *
   * @type {object}
   * @memberof ApiAnalysisAssetHoldingGet200ResponseDataHoldingAnalysis
   */
  period_summary?: object
}
