/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiAssetTypesIdDelete200Response
 */
export interface ApiAssetTypesIdDelete200Response {
    /**
     * 
     * @type {number}
     * @memberof ApiAssetTypesIdDelete200Response
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiAssetTypesIdDelete200Response
     */
    'message'?: string;
    /**
     * 
     * @type {object}
     * @memberof ApiAssetTypesIdDelete200Response
     */
    'data'?: object | null;
}

