/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ApiTransactionsCashSummaryGet200ResponseData
 */
export interface ApiTransactionsCashSummaryGet200ResponseData {
  /**
   * 总现金金额
   * @type {number}
   * @memberof ApiTransactionsCashSummaryGet200ResponseData
   */
  total_cash?: number
  /**
   * 当月支出
   * @type {number}
   * @memberof ApiTransactionsCashSummaryGet200ResponseData
   */
  monthly_expense?: number
  /**
   * 当月收入
   * @type {number}
   * @memberof ApiTransactionsCashSummaryGet200ResponseData
   */
  monthly_income?: number
  /**
   * 净现金流（收入-支出）
   * @type {number}
   * @memberof ApiTransactionsCashSummaryGet200ResponseData
   */
  net_flow?: number
}
