/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ApiAnalysisDailyCashBalanceGet200ResponseDataAnalysisPeriod
 */
export interface ApiAnalysisDailyCashBalanceGet200ResponseDataAnalysisPeriod {
  /**
   *
   * @type {string}
   * @memberof ApiAnalysisDailyCashBalanceGet200ResponseDataAnalysisPeriod
   */
  start_date?: string
  /**
   *
   * @type {string}
   * @memberof ApiAnalysisDailyCashBalanceGet200ResponseDataAnalysisPeriod
   */
  end_date?: string
  /**
   *
   * @type {number}
   * @memberof ApiAnalysisDailyCashBalanceGet200ResponseDataAnalysisPeriod
   */
  days?: number
  /**
   *
   * @type {number}
   * @memberof ApiAnalysisDailyCashBalanceGet200ResponseDataAnalysisPeriod
   */
  actual_days?: number
}
