/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ApiAnalysisDailyCashBalanceGet200ResponseDataDailyBalancesInner
 */
export interface ApiAnalysisDailyCashBalanceGet200ResponseDataDailyBalancesInner {
  /**
   *
   * @type {string}
   * @memberof ApiAnalysisDailyCashBalanceGet200ResponseDataDailyBalancesInner
   */
  date?: string
  /**
   *
   * @type {string}
   * @memberof ApiAnalysisDailyCashBalanceGet200ResponseDataDailyBalancesInner
   */
  holding_start?: string
  /**
   *
   * @type {string}
   * @memberof ApiAnalysisDailyCashBalanceGet200ResponseDataDailyBalancesInner
   */
  holding_end?: string
  /**
   *
   * @type {string}
   * @memberof ApiAnalysisDailyCashBalanceGet200ResponseDataDailyBalancesInner
   */
  daily_change?: string
  /**
   *
   * @type {Array<object>}
   * @memberof ApiAnalysisDailyCashBalanceGet200ResponseDataDailyBalancesInner
   */
  transactions?: Array<object>
  /**
   *
   * @type {number}
   * @memberof ApiAnalysisDailyCashBalanceGet200ResponseDataDailyBalancesInner
   */
  transactions_count?: number
  /**
   *
   * @type {boolean}
   * @memberof ApiAnalysisDailyCashBalanceGet200ResponseDataDailyBalancesInner
   */
  has_transactions?: boolean
}
