/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Transaction } from './transaction';

/**
 * 
 * @export
 * @interface ApiTransactionsSellPost201ResponseData
 */
export interface ApiTransactionsSellPost201ResponseData {
    /**
     * 
     * @type {Transaction}
     * @memberof ApiTransactionsSellPost201ResponseData
     */
    'transaction'?: Transaction;
    /**
     * 总收到金额
     * @type {number}
     * @memberof ApiTransactionsSellPost201ResponseData
     */
    'total_received'?: number;
    /**
     * 新的现金余额
     * @type {number}
     * @memberof ApiTransactionsSellPost201ResponseData
     */
    'new_cash_balance'?: number;
}

