/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { PriceDaily } from './price-daily'

/**
 *
 * @export
 * @interface ApiPriceDailyRangePost200Response
 */
export interface ApiPriceDailyRangePost200Response {
  /**
   *
   * @type {number}
   * @memberof ApiPriceDailyRangePost200Response
   */
  code?: number
  /**
   *
   * @type {string}
   * @memberof ApiPriceDailyRangePost200Response
   */
  message?: string
  /**
   *
   * @type {Array<PriceDaily>}
   * @memberof ApiPriceDailyRangePost200Response
   */
  data?: Array<PriceDaily>
}
