/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ApiAssetsGet200ResponseDataItemsInner
 */
export interface ApiAssetsGet200ResponseDataItemsInner {
  /**
   * 资产ID
   * @type {number}
   * @memberof ApiAssetsGet200ResponseDataItemsInner
   */
  id?: number
  /**
   * 资产名称
   * @type {string}
   * @memberof ApiAssetsGet200ResponseDataItemsInner
   */
  name?: string
  /**
   * 资产类型ID
   * @type {number}
   * @memberof ApiAssetsGet200ResponseDataItemsInner
   */
  asset_type_id?: number
  /**
   * 数量
   * @type {number}
   * @memberof ApiAssetsGet200ResponseDataItemsInner
   */
  quantity?: number
  /**
   * 资产编码
   * @type {string}
   * @memberof ApiAssetsGet200ResponseDataItemsInner
   */
  code?: string
  /**
   * 描述
   * @type {string}
   * @memberof ApiAssetsGet200ResponseDataItemsInner
   */
  description?: string
  /**
   * 创建时间
   * @type {string}
   * @memberof ApiAssetsGet200ResponseDataItemsInner
   */
  create_date?: string
  /**
   * 当前价格
   * @type {number}
   * @memberof ApiAssetsGet200ResponseDataItemsInner
   */
  current_price?: number
  /**
   * 平均持仓价格
   * @type {number}
   * @memberof ApiAssetsGet200ResponseDataItemsInner
   */
  average_position_price?: number
  /**
   * 价格变化百分比
   * @type {number}
   * @memberof ApiAssetsGet200ResponseDataItemsInner
   */
  price_change_percentage?: number
}
