/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Transaction } from './transaction'

/**
 *
 * @export
 * @interface ApiTransactionsBuyPost201ResponseData
 */
export interface ApiTransactionsBuyPost201ResponseData {
  /**
   *
   * @type {Transaction}
   * @memberof ApiTransactionsBuyPost201ResponseData
   */
  transaction?: Transaction
  /**
   * 总花费金额
   * @type {number}
   * @memberof ApiTransactionsBuyPost201ResponseData
   */
  total_cost?: number
  /**
   * 剩余现金
   * @type {number}
   * @memberof ApiTransactionsBuyPost201ResponseData
   */
  remaining_cash?: number
}
