/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Asset } from './asset';

/**
 * 
 * @export
 * @interface ApiAssetsPost201Response
 */
export interface ApiAssetsPost201Response {
    /**
     * 
     * @type {number}
     * @memberof ApiAssetsPost201Response
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiAssetsPost201Response
     */
    'message'?: string;
    /**
     * 
     * @type {Asset}
     * @memberof ApiAssetsPost201Response
     */
    'data'?: Asset;
}

