/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ApiAnalysisAssetHoldingGet200ResponseDataAnalysisPeriod } from './api-analysis-asset-holding-get200-response-data-analysis-period'
// May contain unused imports in some cases
// @ts-ignore
import type { ApiAnalysisAssetHoldingGet200ResponseDataAssetInfo } from './api-analysis-asset-holding-get200-response-data-asset-info'
// May contain unused imports in some cases
// @ts-ignore
import type { ApiAnalysisAssetHoldingGet200ResponseDataHoldingAnalysis } from './api-analysis-asset-holding-get200-response-data-holding-analysis'

/**
 *
 * @export
 * @interface ApiAnalysisAssetHoldingGet200ResponseData
 */
export interface ApiAnalysisAssetHoldingGet200ResponseData {
  /**
   *
   * @type {ApiAnalysisAssetHoldingGet200ResponseDataAssetInfo}
   * @memberof ApiAnalysisAssetHoldingGet200ResponseData
   */
  asset_info?: ApiAnalysisAssetHoldingGet200ResponseDataAssetInfo
  /**
   *
   * @type {ApiAnalysisAssetHoldingGet200ResponseDataAnalysisPeriod}
   * @memberof ApiAnalysisAssetHoldingGet200ResponseData
   */
  analysis_period?: ApiAnalysisAssetHoldingGet200ResponseDataAnalysisPeriod
  /**
   *
   * @type {ApiAnalysisAssetHoldingGet200ResponseDataHoldingAnalysis}
   * @memberof ApiAnalysisAssetHoldingGet200ResponseData
   */
  holding_analysis?: ApiAnalysisAssetHoldingGet200ResponseDataHoldingAnalysis
  /**
   *
   * @type {object}
   * @memberof ApiAnalysisAssetHoldingGet200ResponseData
   */
  summary?: object
}
