/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ApiMainPageTotalAssetsHistoryGet200ResponseDataInner
 */
export interface ApiMainPageTotalAssetsHistoryGet200ResponseDataInner {
  /**
   * 日期
   * @type {string}
   * @memberof ApiMainPageTotalAssetsHistoryGet200ResponseDataInner
   */
  date?: string
  /**
   * 当日总资产价值
   * @type {number}
   * @memberof ApiMainPageTotalAssetsHistoryGet200ResponseDataInner
   */
  total_asset_value?: number
}
