/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiPriceDailyRangePostRequest
 */
export interface ApiPriceDailyRangePostRequest {
    /**
     * 资产的唯一标识符
     * @type {number}
     * @memberof ApiPriceDailyRangePostRequest
     */
    'asset_id': number;
    /**
     * 开始日期 (YYYY-MM-DD格式)
     * @type {string}
     * @memberof ApiPriceDailyRangePostRequest
     */
    'start_date': string;
    /**
     * 结束日期 (YYYY-MM-DD格式)
     * @type {string}
     * @memberof ApiPriceDailyRangePostRequest
     */
    'end_date': string;
}

