/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ApiMainPageSummaryGet200ResponseData
 */
export interface ApiMainPageSummaryGet200ResponseData {
  /**
   * 总资产价值
   * @type {number}
   * @memberof ApiMainPageSummaryGet200ResponseData
   */
  total_asset_value?: number
  /**
   * 总盈亏
   * @type {number}
   * @memberof ApiMainPageSummaryGet200ResponseData
   */
  total_profit_loss?: number
  /**
   * 当日盈亏
   * @type {number}
   * @memberof ApiMainPageSummaryGet200ResponseData
   */
  today_profit_loss?: number
  /**
   * 总盈亏百分比
   * @type {number}
   * @memberof ApiMainPageSummaryGet200ResponseData
   */
  total_profit_loss_percentage?: number
  /**
   * 当日盈亏百分比
   * @type {number}
   * @memberof ApiMainPageSummaryGet200ResponseData
   */
  today_profit_loss_percentage?: number
}
