/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ApiTransactionsGet200ResponseDataItemsInner
 */
export interface ApiTransactionsGet200ResponseDataItemsInner {
  /**
   * 交易记录ID
   * @type {number}
   * @memberof ApiTransactionsGet200ResponseDataItemsInner
   */
  id?: number
  /**
   * 资产ID
   * @type {number}
   * @memberof ApiTransactionsGet200ResponseDataItemsInner
   */
  asset_id?: number
  /**
   * 交易类型(IN=入库, OUT=出库)
   * @type {string}
   * @memberof ApiTransactionsGet200ResponseDataItemsInner
   */
  transaction_type?: ApiTransactionsGet200ResponseDataItemsInnerTransactionTypeEnum
  /**
   * 交易数量
   * @type {number}
   * @memberof ApiTransactionsGet200ResponseDataItemsInner
   */
  quantity?: number
  /**
   * 交易单价
   * @type {number}
   * @memberof ApiTransactionsGet200ResponseDataItemsInner
   */
  price?: number
  /**
   * 交易日期
   * @type {string}
   * @memberof ApiTransactionsGet200ResponseDataItemsInner
   */
  transaction_date?: string
  /**
   * 交易后资产余额
   * @type {number}
   * @memberof ApiTransactionsGet200ResponseDataItemsInner
   */
  holding?: number
  /**
   * 描述
   * @type {string}
   * @memberof ApiTransactionsGet200ResponseDataItemsInner
   */
  description?: string
  /**
   * 资产名称
   * @type {string}
   * @memberof ApiTransactionsGet200ResponseDataItemsInner
   */
  asset_name?: string
  /**
   * 资产代码
   * @type {string}
   * @memberof ApiTransactionsGet200ResponseDataItemsInner
   */
  asset_code?: string
}

export const ApiTransactionsGet200ResponseDataItemsInnerTransactionTypeEnum = {
  In: 'IN',
  Out: 'OUT',
} as const

export type ApiTransactionsGet200ResponseDataItemsInnerTransactionTypeEnum =
  (typeof ApiTransactionsGet200ResponseDataItemsInnerTransactionTypeEnum)[keyof typeof ApiTransactionsGet200ResponseDataItemsInnerTransactionTypeEnum]
