/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ApiMainPageTotalAssetsHistoryGet200ResponseDataInner } from './api-main-page-total-assets-history-get200-response-data-inner'

/**
 *
 * @export
 * @interface ApiMainPageTotalAssetsHistoryGet200Response
 */
export interface ApiMainPageTotalAssetsHistoryGet200Response {
  /**
   *
   * @type {number}
   * @memberof ApiMainPageTotalAssetsHistoryGet200Response
   */
  code?: number
  /**
   *
   * @type {string}
   * @memberof ApiMainPageTotalAssetsHistoryGet200Response
   */
  message?: string
  /**
   *
   * @type {Array<ApiMainPageTotalAssetsHistoryGet200ResponseDataInner>}
   * @memberof ApiMainPageTotalAssetsHistoryGet200Response
   */
  data?: Array<ApiMainPageTotalAssetsHistoryGet200ResponseDataInner>
}
