/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AssetTotalsResponseData } from './asset-totals-response-data';

/**
 * 
 * @export
 * @interface AssetTotalsResponse
 */
export interface AssetTotalsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof AssetTotalsResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {AssetTotalsResponseData}
     * @memberof AssetTotalsResponse
     */
    'data'?: AssetTotalsResponseData;
}

