/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Asset } from './asset';
// May contain unused imports in some cases
// @ts-ignore
import type { AssetTypeResponseDataSummary } from './asset-type-response-data-summary';

/**
 * 
 * @export
 * @interface AssetTypeResponseData
 */
export interface AssetTypeResponseData {
    /**
     * Analysis date
     * @type {string}
     * @memberof AssetTypeResponseData
     */
    'date'?: string;
    /**
     * Asset type name
     * @type {string}
     * @memberof AssetTypeResponseData
     */
    'assetType'?: string;
    /**
     * Total value in USD
     * @type {number}
     * @memberof AssetTypeResponseData
     */
    'totalValueUSD'?: number;
    /**
     * Total price in USD
     * @type {number}
     * @memberof AssetTypeResponseData
     */
    'totalPrice'?: number;
    /**
     * 
     * @type {Array<Asset>}
     * @memberof AssetTypeResponseData
     */
    'assets'?: Array<Asset>;
    /**
     * 
     * @type {AssetTypeResponseDataSummary}
     * @memberof AssetTypeResponseData
     */
    'summary'?: AssetTypeResponseDataSummary;
}

