/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PriceDaily
 */
export interface PriceDaily {
  /**
   * 价格记录ID
   * @type {number}
   * @memberof PriceDaily
   */
  id?: number
  /**
   * 资产ID
   * @type {number}
   * @memberof PriceDaily
   */
  asset_id: number
  /**
   * 价格日期
   * @type {string}
   * @memberof PriceDaily
   */
  date: string
  /**
   * 当日价格
   * @type {number}
   * @memberof PriceDaily
   */
  price: number
  /**
   * 记录创建时间
   * @type {string}
   * @memberof PriceDaily
   */
  create_date?: string
}
