/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Date range used for filtering (null if no date filter applied)
 * @export
 * @interface TransactionsByTypeResponseDataDateRange
 */
export interface TransactionsByTypeResponseDataDateRange {
  /**
   * Start date of the filter range
   * @type {string}
   * @memberof TransactionsByTypeResponseDataDateRange
   */
  start_date?: string
  /**
   * End date of the filter range
   * @type {string}
   * @memberof TransactionsByTypeResponseDataDateRange
   */
  end_date?: string
}
