/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Transaction } from './transaction'
// May contain unused imports in some cases
// @ts-ignore
import type { TransactionsByTypeResponseDataDateRange } from './transactions-by-type-response-data-date-range'
// May contain unused imports in some cases
// @ts-ignore
import type { TransactionsByTypeResponseDataPagination } from './transactions-by-type-response-data-pagination'
// May contain unused imports in some cases
// @ts-ignore
import type { TransactionsByTypeResponseDataSummary } from './transactions-by-type-response-data-summary'

/**
 *
 * @export
 * @interface TransactionsByTypeResponseData
 */
export interface TransactionsByTypeResponseData {
  /**
   * Asset type ID
   * @type {number}
   * @memberof TransactionsByTypeResponseData
   */
  asset_type_id?: number
  /**
   * Asset type name
   * @type {string}
   * @memberof TransactionsByTypeResponseData
   */
  asset_type_name?: string
  /**
   *
   * @type {TransactionsByTypeResponseDataDateRange}
   * @memberof TransactionsByTypeResponseData
   */
  date_range?: TransactionsByTypeResponseDataDateRange
  /**
   * Total number of transactions
   * @type {number}
   * @memberof TransactionsByTypeResponseData
   */
  total_transactions?: number
  /**
   *
   * @type {Array<Transaction>}
   * @memberof TransactionsByTypeResponseData
   */
  transactions?: Array<Transaction>
  /**
   *
   * @type {TransactionsByTypeResponseDataSummary}
   * @memberof TransactionsByTypeResponseData
   */
  summary?: TransactionsByTypeResponseDataSummary
  /**
   *
   * @type {TransactionsByTypeResponseDataPagination}
   * @memberof TransactionsByTypeResponseData
   */
  pagination?: TransactionsByTypeResponseDataPagination
}
