/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * 交易记录ID
     * @type {number}
     * @memberof Transaction
     */
    'id'?: number;
    /**
     * 资产ID
     * @type {number}
     * @memberof Transaction
     */
    'asset_id': number;
    /**
     * 交易类型(IN=入库, OUT=出库)
     * @type {string}
     * @memberof Transaction
     */
    'transaction_type': TransactionTransactionTypeEnum;
    /**
     * 交易数量
     * @type {number}
     * @memberof Transaction
     */
    'quantity': number;
    /**
     * 交易单价
     * @type {number}
     * @memberof Transaction
     */
    'price': number;
    /**
     * 交易日期
     * @type {string}
     * @memberof Transaction
     */
    'transaction_date': string;
    /**
     * 交易后资产余额
     * @type {number}
     * @memberof Transaction
     */
    'holding': number;
    /**
     * 描述
     * @type {string}
     * @memberof Transaction
     */
    'description'?: string;
}

export const TransactionTransactionTypeEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;

export type TransactionTransactionTypeEnum = typeof TransactionTransactionTypeEnum[keyof typeof TransactionTransactionTypeEnum];


