/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Transaction
 */
export interface Transaction {
  /**
   * Transaction ID
   * @type {number}
   * @memberof Transaction
   */
  id?: number
  /**
   * Asset ID
   * @type {number}
   * @memberof Transaction
   */
  asset_id?: number
  /**
   * Asset name
   * @type {string}
   * @memberof Transaction
   */
  asset_name?: string
  /**
   * Asset code
   * @type {string}
   * @memberof Transaction
   */
  asset_code?: string
  /**
   * Asset type name
   * @type {string}
   * @memberof Transaction
   */
  asset_type_name?: string
  /**
   * Transaction type (IN = add, OUT = remove)
   * @type {string}
   * @memberof Transaction
   */
  transaction_type?: TransactionTransactionTypeEnum
  /**
   * Quantity involved in transaction
   * @type {number}
   * @memberof Transaction
   */
  quantity?: number
  /**
   * Unit price at time of transaction
   * @type {number}
   * @memberof Transaction
   */
  price?: number
  /**
   * Date and time of transaction
   * @type {string}
   * @memberof Transaction
   */
  transaction_date?: string
  /**
   * Asset balance after this transaction
   * @type {number}
   * @memberof Transaction
   */
  holding?: number
  /**
   * Transaction description or notes
   * @type {string}
   * @memberof Transaction
   */
  description?: string
}

export const TransactionTransactionTypeEnum = {
  In: 'IN',
  Out: 'OUT',
} as const

export type TransactionTransactionTypeEnum =
  (typeof TransactionTransactionTypeEnum)[keyof typeof TransactionTransactionTypeEnum]
