/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TransactionsByTypeResponseDataSummary
 */
export interface TransactionsByTypeResponseDataSummary {
  /**
   * Total quantity added (IN transactions)
   * @type {number}
   * @memberof TransactionsByTypeResponseDataSummary
   */
  total_in_quantity?: number
  /**
   * Total quantity removed (OUT transactions)
   * @type {number}
   * @memberof TransactionsByTypeResponseDataSummary
   */
  total_out_quantity?: number
  /**
   * Net quantity (IN - OUT)
   * @type {number}
   * @memberof TransactionsByTypeResponseDataSummary
   */
  net_quantity?: number
  /**
   * Total value of IN transactions
   * @type {number}
   * @memberof TransactionsByTypeResponseDataSummary
   */
  total_in_value?: number
  /**
   * Total value of OUT transactions
   * @type {number}
   * @memberof TransactionsByTypeResponseDataSummary
   */
  total_out_value?: number
  /**
   * Net value (IN - OUT)
   * @type {number}
   * @memberof TransactionsByTypeResponseDataSummary
   */
  net_value?: number
}
