/* tslint:disable */
/* eslint-disable */
/**
 * Portfolio Management API
 * A comprehensive API for managing investment portfolios, tracking assets, and analyzing portfolio performance. Supports multiple asset types including cash, stocks, bonds, cryptocurrencies, foreign currencies, and futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@portfoliomanagement.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TransactionsByTypeResponseDataPagination
 */
export interface TransactionsByTypeResponseDataPagination {
  /**
   * Current page number
   * @type {number}
   * @memberof TransactionsByTypeResponseDataPagination
   */
  page?: number
  /**
   * Number of items per page
   * @type {number}
   * @memberof TransactionsByTypeResponseDataPagination
   */
  limit?: number
  /**
   * Total number of pages
   * @type {number}
   * @memberof TransactionsByTypeResponseDataPagination
   */
  total_pages?: number
  /**
   * Whether there is a next page
   * @type {boolean}
   * @memberof TransactionsByTypeResponseDataPagination
   */
  has_next?: boolean
  /**
   * Whether there is a previous page
   * @type {boolean}
   * @memberof TransactionsByTypeResponseDataPagination
   */
  has_prev?: boolean
}
